[package]
edition = "2024"
name = "piwi"
version = "0.0.1"

[dependencies]
alloy-primitives = "0.8"
clap = { version = "4.5", features = ["derive"] }
hex = "0.4"
rand = "0.9"
rayon = "1.10"
thiserror = "2"
